Project Portfolio
CS2103AUG2017-F10-B1/main pull request #136
Opened 2017-11-09 19:22 UTC by TanYikai

2017-11-09 23:10 UTC, joanneong commented on docs/team/projectPortfolio.adoc
> +== Project: AddressBook - Level 4
Wrong project, go and copy Zhen Yong's

2017-11-10 00:23 UTC, wenmogu requested changes

2017-11-10 00:23 UTC, wenmogu commented on docs/UserGuide.adoc
>  === Adding a relationship between two persons: `addRelationship`
please put a blank line there

2017-11-10 00:23 UTC, wenmogu commented on docs/UserGuide.adoc
>  === Editing a person : `edit`
same here

2017-11-10 00:23 UTC, wenmogu commented on docs/team/projectPortfolio.adoc
> +== Project: AddressBook - Level 4
it shld be intelliJ...this description can copy from others' portfolio in the main repo

2017-11-10 00:23 UTC, wenmogu commented on docs/team/projectPortfolio.adoc
> +*Code contributed*: [https://github.com/CS2103AUG2017-F10-B1/main/tree/master/collated[Functional code]] [https://github.com/CS2103AUG2017-F10-B1/main/tree/master/collated[Test code]] {give links to
the code link to be the link to ur collated code file, so it shld be something like https://github.com/CS2103AUG2017-F10-B1/main/blob/master/collated/main/TanYikai.md

2017-11-10 00:23 UTC, wenmogu commented on docs/team/projectPortfolio.adoc
> +include::../DeveloperGuide.adoc[tag=]
what happened to the tag...

2017-11-10 01:58 UTC, wenmogu approved these changes

2017-11-10 02:04 UTC, merged