Add upcoming features to user guide
CS2103AUG2017-F10-B1/main pull request #70
Opened 2017-10-19 09:53 UTC by Xenonym

2017-10-19 20:21 UTC, joanneong requested changes

2017-10-19 20:21 UTC, joanneong commented on docs/UserGuide.adoc
> +=== Listing all related persons : `listrelated`
Should be `List`

2017-10-19 20:21 UTC, joanneong commented on docs/UserGuide.adoc
> +=== View shortest relationship path between to persons : `viewpath`
Should be `two`

2017-10-20 01:30 UTC, Xenonym commented on docs/UserGuide.adoc
> +=== Listing all related persons : `listrelated`
The list command already exists...

2017-10-20 03:22 UTC, joanneong approved these changes

2017-10-20 13:22 UTC, merged